config/routes.rb
Rails.application.routes.draw do

  resources :regdetails
  resources :courses
  resources :semesters
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }
  root "regdetails#index"

end

app/models/regdetail.rb
class Regdetail < ApplicationRecord
  belongs_to :user
  belongs_to :semester
  belongs_to :course
end

app/controllers/regdetails_controller.rb
class RegdetailsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_regdetail, only: [:show, :edit, :update, :destroy]

  # GET /regdetails
  # GET /regdetails.json
  def index
    @regdetails = Regdetail.all
  end

  # GET /regdetails/1
  # GET /regdetails/1.json
  def show
  end

  # GET /regdetails/new
  def new
    @semesters = Semester.pluck(:name, :id)
    @courses = Semester.find(1).courses
  end

  # GET /regdetails/1/edit
  def edit
  end

  # POST /regdetails
  # POST /regdetails.json
  def create
    # @regdetail = Regdetail.new(regdetail_params)
    #
    # respond_to do |format|
    #   if @regdetail.save
    #     format.html { redirect_to @regdetail, notice: 'Regdetail was successfully created.' }
    #     format.json { render :show, status: :created, location: @regdetail }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @regdetail.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /regdetails/1
  # PATCH/PUT /regdetails/1.json
  def update
    respond_to do |format|
      if @regdetail.update(regdetail_params)
        format.html { redirect_to @regdetail, notice: 'Regdetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @regdetail }
      else
        format.html { render :edit }
        format.json { render json: @regdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regdetails/1
  # DELETE /regdetails/1.json
  def destroy
    @regdetail.destroy
    respond_to do |format|
      format.html { redirect_to regdetails_url, notice: 'Regdetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regdetail
      @regdetail = Regdetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def regdetail_params
      params.require(:regdetail).permit(:user_id, :semester_id, :course_id, :gpa)
    end
end

app/helpers/regdetails_helper.rb
module RegdetailsHelper
end

app/views/regdetails/_course_list.html.erb
<table class="table">
  <thead>
  <tr>
    <th>name</th>
    <th>code</th>
    <th>credit</th>
  </tr>
  </thead>
  <tbody>
  <% @courses.each do |c| %>
    <tr>
      <td>.name</td>
      <td>c.code</td>
      <td>c.credit</td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/regdetails/_form.html.erb
<%= form_tag(regdetails_path, method: "post") do %>

    <%= select_tag "semester", options_for_select(@semesters) %>
    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Code</th>
        <th>Credit</th>
      </tr>
      </thead>
      <tbody>
      <% @courses.each do |c|%>
      <tr>
        <td><%= c.name %></td>
        <td><%= c.credit %></td>
        <td><%= check_box_tag c.name,c.id %></td>

      </tr>
      <% end %>
      </tbody>
    </table>

<%= submit_tag "Submit" %>
<% end %>

app/views/regdetails/edit.html.erb
<h1>Editing Regdetail</h1>

<%= render 'form', regdetail: @regdetail %>

<%= link_to 'Show', @regdetail %> |
<%= link_to 'Back', regdetails_path %>

app/views/regdetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Regdetails</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Semester</th>
      <th>Course</th>
      <th>Gpa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regdetails.each do |regdetail| %>
      <tr>
        <td><%= regdetail.user %></td>
        <td><%= regdetail.semester %></td>
        <td><%= regdetail.course %></td>
        <td><%= regdetail.gpa %></td>
        <td><%= link_to 'Show', regdetail %></td>
        <td><%= link_to 'Edit', edit_regdetail_path(regdetail) %></td>
        <td><%= link_to 'Destroy', regdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Regdetail', new_regdetail_path %>

app/views/regdetails/new.html.erb
<h1>New Regdetail</h1>

<%= render 'form'%>

<%= link_to 'Back', regdetails_path %>

app/views/regdetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @regdetail.user %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @regdetail.semester %>
</p>

<p>
  <strong>Course:</strong>
  <%= @regdetail.course %>
</p>

<p>
  <strong>Gpa:</strong>
  <%= @regdetail.gpa %>
</p>

<%= link_to 'Edit', edit_regdetail_path(@regdetail) %> |
<%= link_to 'Back', regdetails_path %>